name: Nekton CI

on:
  push:
    branches:
      - master

jobs:
  component-library-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          npx yarn
          npx lerna bootstrap
      - name: Lint
        run: npx yarn workspace @elliott/component-library run lint
      - name: Build
        run: npx yarn workspace @elliott/component-library run build-storybook
      - name: Unit tests
        run: npx jest
