name: Nekton CI

on:
  push:
    branches:
      - master

jobs:
  component-library-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          npx yarn
          npx lerna bootstrap
      - name: Lint
        run: npx yarn workspace @nekton/component-library run lint
      - name: Build
        run: npx yarn workspace @nekton/component-library run build-storybook
      - name: Unit tests
        run: npx jest
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_COMPONENT_LIBRARY_IMAGE }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: ./packages/component-library
        env:
          CI: true
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST}}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_DROPLET_SSH }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
            docker kill ${{ secrets.DOCKER_CONTAINER_NAME }}
            docker rm ${{ secrets.DOCKER_CONTAINER_NAME }}
            docker ps --all
            docker pull ${{ secrets.DOCKER_COMPONENT_LIBRARY_IMAGE }}
            docker run --name ${{ secrets.DOCKER_CONTAINER_NAME }} -p 80:80 -d ${{ secrets.DOCKER_COMPONENT_LIBRARY_IMAGE }}
            docker ps --all
            exit
